image:
  file: .gitpod/Dockerfile

tasks:
  - command: |
      docker login "$(cut -d '/' -f -1 <<< $IMG)" \
        --username "${REGISTRY_USERNAME}" \
        --password "${REGISTRY_TOKEN}"

vscode:
  extensions:
    - donjayamanne.git-extension-pack
    - EditorConfig.EditorConfig
    - golang.go
